// Placeholder data for admin dashboard components
// Field names align with planned Prisma models

export const PLACEHOLDER_ADMIN_STATS = {
  openMaterialRequests: 12,
  pendingProcurements: 5,
  activeCheckouts: 8,
  machinesInMaintenance: 3,
  newUsersThisWeek: 4,
  todaysBookings: 15,
};

export const PLACEHOLDER_LABS_ADMIN = [
  {
    id: "lab-1",
    name: "Electronics Lab",
    slug: "electronics-lab",
    location: "Building A, Floor 2",
    divisionsCount: 3,
    status: "active",
  },
  {
    id: "lab-2",
    name: "Robotics Lab",
    slug: "robotics-lab",
    location: "Building B, Floor 1",
    divisionsCount: 5,
    status: "active",
  },
  {
    id: "lab-3",
    name: "Woodworking Shop",
    slug: "woodworking-shop",
    location: "Building C, Ground",
    divisionsCount: 2,
    status: "active",
  },
  {
    id: "lab-4",
    name: "3D Printing Lab",
    slug: "3d-printing-lab",
    location: "Building A, Floor 3",
    divisionsCount: 1,
    status: "maintenance",
  },
];

export const PLACEHOLDER_ASSETS_ADMIN = [
  {
    id: "asset-1",
    name: "CNC Router",
    lab: "Woodworking Shop",
    division: "Cutting",
    kind: "Machine",
    status: "available",
    lastActivity: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "asset-2",
    name: "Arduino Uno Kit",
    lab: "Electronics Lab",
    division: "Prototyping",
    kind: "Equipment",
    status: "in-use",
    lastActivity: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: "asset-3",
    name: "3D Printer - Prusa i3",
    lab: "3D Printing Lab",
    division: "Additive",
    kind: "Machine",
    status: "maintenance",
    lastActivity: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: "asset-4",
    name: "Soldering Station",
    lab: "Electronics Lab",
    division: "Soldering",
    kind: "Equipment",
    status: "available",
    lastActivity: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: "asset-5",
    name: "Oscilloscope",
    lab: "Electronics Lab",
    division: "Testing",
    kind: "Tool",
    status: "available",
    lastActivity: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: "asset-6",
    name: "Laser Cutter",
    lab: "Woodworking Shop",
    division: "Engraving",
    kind: "Machine",
    status: "in-use",
    lastActivity: new Date(Date.now() - 15 * 60 * 1000),
  },
];

export const PLACEHOLDER_MATERIAL_REQUESTS_ADMIN = [
  {
    id: "mr-1",
    materialName: "Acrylic Sheet (5mm)",
    requestedBy: "John Doe",
    quantity: 10,
    unit: "sheets",
    requestedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    status: "pending",
  },
  {
    id: "mr-2",
    materialName: "Copper Wire (1mm)",
    requestedBy: "Jane Smith",
    quantity: 50,
    unit: "m",
    requestedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    status: "pending",
  },
  {
    id: "mr-3",
    materialName: "PLA Filament (1kg)",
    requestedBy: "Mike Chen",
    quantity: 5,
    unit: "rolls",
    requestedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    status: "approved",
  },
  {
    id: "mr-4",
    materialName: "Plywood (12mm)",
    requestedBy: "Sarah Wilson",
    quantity: 2,
    unit: "sheets",
    requestedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    status: "pending",
  },
];

export const PLACEHOLDER_PROCUREMENT_ADMIN = [
  {
    id: "po-1",
    itemName: "Resistor Assortment Pack",
    vendor: "Electronics Supplier Inc",
    quantity: 1000,
    estimatedCost: 2500,
    requestedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: "pending",
  },
  {
    id: "po-2",
    itemName: "Safety Goggles (20 units)",
    vendor: "Safety Plus Ltd",
    quantity: 20,
    estimatedCost: 3000,
    requestedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    status: "approved",
  },
  {
    id: "po-3",
    itemName: "NEMA 17 Stepper Motors",
    vendor: "Industrial Components Co",
    quantity: 50,
    estimatedCost: 12500,
    requestedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "pending",
  },
  {
    id: "po-4",
    itemName: "Aluminum Extrusion Profile",
    vendor: "Structural Materials Ltd",
    quantity: 100,
    estimatedCost: 8000,
    requestedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    status: "in-transit",
  },
];
